sudo: false

language:
- php
- node_js

php:
    - 7.0

node_js:
- stable
env:
  global:
  - WP_MULTISITE=1
  - PHANTOMJS_CDNURL='http://files.urldocs.com/share/phantomjs'
  - SITE_UUID='ecc3a39c-c237-415b-b8fc-b00f58e1eb69'

branches:
  only:
  - production
before_install:
- openssl aes-256-cbc -K $encrypted_e20a70004f31_key -iv $encrypted_e20a70004f31_iv
  -in dev-scripts/github_deploy_key.enc -out dev-scripts/github_deploy_key -d
- WP_VERSION=$( cat ./wp-includes/version.php | grep 'wp_version =' | grep -oE '[0-9][0-9]*\.[0-9][0-9]*(\.[0-9][0-9]*)*(-[0-9a-z]*)*'
  )
- echo "WP_VERSION=$WP_VERSION"
install:
- export DEV_LIB_PATH=dev-lib
- if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname
  $( readlink .travis.yml ) ); fi
- if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/OWL-Labs/wp-dev-lib.git
  $DEV_LIB_PATH; fi
- set -x
- source $DEV_LIB_PATH/travis.install.sh
script:
- source $DEV_LIB_PATH/travis.script.sh
after_script:
- source $DEV_LIB_PATH/travis.after_script.sh
after_success:
  provider: releases
  api_key:
    secure: Ifdvkr/pPrqHJTh4SMhabEJB4O5HS8nHn8YC24T/nx5DcxW5BcmpGG1ul9WzPcCtDsFWo+vAGawjf/Ex05q9VniXLToKhUu8pT36n0pLQDbfSRmmSE6WELUJoF5643tReYa+FD41O0fTqve/65pzwC2CvrUqSLx1bArs1N2igN+6Qw4IVzddh7O/Srol6uRzoWkRtkJPHD+Ena2jBfXQaORHwPXKLtUiNZI/r8tRnVCxvXy6LE/IRfwqYarRm+2j2gS1pCoTICv92SlLoOueccLVJPaqXfRVfCTppudHrJi3XiqTc38uH6X6sldW4GwP/zOhTmjbPLSiWlSkWYsc0wWKY71HOmq6+KTwkhYCZGIKqTwyoJi5+SBfUKFvEOlS4GvI4SywLgSXvO1gYTblubkHPYWIRuijEZnExvnRwrjFsb0PldUj6xeLI0v0UHZHo4vzPxLoAFt+InSZSR8Aizp+JM37UC9k1ddH3yL/UMtMJbI4/ZMLt5kj1YIDyYgUb66GP5NkA2G2UH2NBfkfXeqGSRVMg4X0QnXZutf9ztq0UgMD4T11gpatS007DSs3G4UDxNZKdxo7Y4akxLXVGVw+hCzwYu/9sWzfcNfgZtA+aoKdkuvRQVfFL39nkq7U7kJVXbrlEpA2FLkT69Cx0rBrKpoP2imV5lQtWMAI/Y4=

  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q git://github.com/OWL-Labs/WordPress-Pantheon.git --tags
  - ls -R

    #- git config --global user.email "talk@quietnoise.com"
    #- git config --global user.name "Your Name"
    #- export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
    #- git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
    #- git push -q https://github.com/OWL-Labs/WordPress-Pantheon.git --tags
    #- ls -R

deploy:
  provider: releases
  api_key:
    secure: Ifdvkr/pPrqHJTh4SMhabEJB4O5HS8nHn8YC24T/nx5DcxW5BcmpGG1ul9WzPcCtDsFWo+vAGawjf/Ex05q9VniXLToKhUu8pT36n0pLQDbfSRmmSE6WELUJoF5643tReYa+FD41O0fTqve/65pzwC2CvrUqSLx1bArs1N2igN+6Qw4IVzddh7O/Srol6uRzoWkRtkJPHD+Ena2jBfXQaORHwPXKLtUiNZI/r8tRnVCxvXy6LE/IRfwqYarRm+2j2gS1pCoTICv92SlLoOueccLVJPaqXfRVfCTppudHrJi3XiqTc38uH6X6sldW4GwP/zOhTmjbPLSiWlSkWYsc0wWKY71HOmq6+KTwkhYCZGIKqTwyoJi5+SBfUKFvEOlS4GvI4SywLgSXvO1gYTblubkHPYWIRuijEZnExvnRwrjFsb0PldUj6xeLI0v0UHZHo4vzPxLoAFt+InSZSR8Aizp+JM37UC9k1ddH3yL/UMtMJbI4/ZMLt5kj1YIDyYgUb66GP5NkA2G2UH2NBfkfXeqGSRVMg4X0QnXZutf9ztq0UgMD4T11gpatS007DSs3G4UDxNZKdxo7Y4akxLXVGVw+hCzwYu/9sWzfcNfgZtA+aoKdkuvRQVfFL39nkq7U7kJVXbrlEpA2FLkT69Cx0rBrKpoP2imV5lQtWMAI/Y4=
  file: README.md
  skip_cleanup: true
  on:
    repo: OWL-Labs/WordPress-Pantheon
    branch: production
    tags: true
