sudo: false

language:
    - php
    - node_js

php:
    - 5.5

node_js:
    - stable

env:
    global:
        - WP_MULTISITE=1
        - PHANTOMJS_CDNURL='http://files.urldocs.com/share/phantomjs'
        - SITE_UUID='ecc3a39c-c237-415b-b8fc-b00f58e1eb69'

before_install:
    - WP_VERSION=$( cat ./wp-includes/version.php | grep 'wp_version =' | grep -oE '[0-9][0-9]*\.[0-9][0-9]*(\.[0-9][0-9]*)*(-[0-9a-z]*)*' )
    - echo "WP_VERSION=$WP_VERSION"

install:
    - export DEV_LIB_PATH=dev-lib
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/OWL-Labs/wp-dev-lib.git $DEV_LIB_PATH; fi
    - set -x
    - source $DEV_LIB_PATH/travis.install.sh
sudo: false

language:
    - php
    - node_js

php:
    - 5.5

node_js:
    - stable

env:
    global:
        - WP_MULTISITE=1
        - PHANTOMJS_CDNURL='http://files.urldocs.com/share/phantomjs'
        - SITE_UUID='ecc3a39c-c237-415b-b8fc-b00f58e1eb69'

branches:
    only:
        - master
        - production

before_install:
    - WP_VERSION=$( cat ./wp-includes/version.php | grep 'wp_version =' | grep -oE '[0-9][0-9]*\.[0-9][0-9]*(\.[0-9][0-9]*)*(-[0-9a-z]*)*' )
    - echo "WP_VERSION=$WP_VERSION"

install:
    - export DEV_LIB_PATH=dev-lib
    - if [ ! -e "$DEV_LIB_PATH" ] && [ -L .travis.yml ]; then export DEV_LIB_PATH=$( dirname $( readlink .travis.yml ) ); fi
    - if [ ! -e "$DEV_LIB_PATH" ]; then git clone https://github.com/OWL-Labs/wp-dev-lib.git $DEV_LIB_PATH; fi
    - set -x
    - source $DEV_LIB_PATH/travis.install.sh

script:
    - source $DEV_LIB_PATH/travis.script.sh

after_script:
    - source $DEV_LIB_PATH/travis.after_script.sh

after_success:
    - |
          if [ $TRAVIS_BRANCH == 'master' ] && [ $TRAVIS_PULL_REQUEST == 'false' ]; then
              git config --global user.name "Travis Owl Repo"
              git config --global user.email "merenuou@gmail.com"
              ssh-keyscan -p 2222 codeserver.dev.$PANTHEON_UUID.drush.in >> ~/.ssh/known_hosts
              git remote add pantheon ssh://codeserver.dev.$PANTHEON_UUID@codeserver.dev.$PANTHEON_UUID.drush.in:2222/~/repository.git
              git fetch pantheon
              git merge -s ours -m "Merge changes from pantheon using ours merge strategy" pantheon/master
              git push pantheon HEAD:master
          fi
after_success:
    - |
          if [ $TRAVIS_BRANCH == 'master' ] && [ $TRAVIS_PULL_REQUEST == 'false' ]; then
              git config --global user.name "Travis Owl Repo"
              git config --global user.email "merenuou@gmail.com"
              ssh-keyscan -p 2222 codeserver.dev.$SITE_UUID.drush.in >> ~/.ssh/known_hosts
              git remote add pantheonUpstream ssh://codeserver.dev.$SITE_UUID@codeserver.dev.$SITE_UUID.drush.in:2222/~/repository.git
              git fetch pantheonUpstream
              git merge -s ours -m "Merge changes from pantheon using the ours merge strategy" pantheonUpstream/master
              git push pantheon HEAD:master
          fi

script:
    - source $DEV_LIB_PATH/travis.script.sh

after_script:
    - source $DEV_LIB_PATH/travis.after_script.sh

after_success:
    - |
          if [ $TRAVIS_BRANCH == 'master' ] && [ $TRAVIS_PULL_REQUEST == 'false' ]; then
              git config --global user.name "Travis Owl Repo"
              git config --global user.email "merenuou@gmail.com"
              ssh-keyscan -p 2222 codeserver.dev.$PANTHEON_UUID.drush.in >> ~/.ssh/known_hosts
              git remote add pantheon ssh://codeserver.dev.$PANTHEON_UUID@codeserver.dev.$PANTHEON_UUID.drush.in:2222/~/repository.git
              git fetch pantheon
              git merge -s ours -m "Merge changes from pantheon using ours merge strategy" pantheon/master
              git push pantheon HEAD:master
          fi
after_success:
    - |
          if [ $TRAVIS_BRANCH == 'production' ] && [ $TRAVIS_PULL_REQUEST == 'false' ]; then
              git config --global user.name "Travis Owl Repo"
              git config --global user.email "merenuou@gmail.com"
              ssh-keyscan -p 2222 codeserver.dev.$SITE_UUID.drush.in >> ~/.ssh/known_hosts
              git remote add pantheonUpstream ssh://codeserver.dev.$SITE_UUID@codeserver.dev.$SITE_UUID.drush.in:2222/~/repository.git
              git fetch pantheonUpstream
              git merge -s ours -m "Merge changes from pantheon using the ours merge strategy" pantheonUpstream/master
              git push pantheon HEAD:master
          fi
